
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='rasam',
    version='0.4.0',
    description='Rasa Improved',
    python_requires='<3.9,>=3.6.2',
    project_urls={"repository": "https://github.com/roniemartinez/rasam"},
    author='Ronie Martinez',
    author_email='ronmarti18@gmail.com',
    license='MIT',
    keywords='URL extractor for Rasa Regex entity extractor for Rasa Placeholder importer for Rasa',
    classifiers=['Development Status :: 3 - Alpha', 'License :: OSI Approved :: MIT License', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: Implementation :: CPython'],
    packages=['rasam'],
    package_dir={"": "."},
    package_data={},
    install_requires=['faker==8.*,>=8.1.4', 'rasa==2.*,>=2.6.1', 'urlextract==1.*,>=1.2.0'],
    extras_require={"dev": ["autoflake==1.*,>=1.3.1", "black==21.*,>=21.5.0.b1", "codecov==2.*,>=2.0.22", "dephell==0.*,>=0.8.2", "flake8==3.*,>=3.7.9", "isort==5.*,>=5.8.0", "mypy==0.*,>=0.812.0", "pytest==6.*,>=6.2.4", "pytest-asyncio==0.*,>=0.15.1", "pytest-cov==2.*,>=2.8.1", "tomlkit==0.7.0"]},
)
